### ISSUE TITLE
LESS build failure

### ISSUE THREAD

**Issue by jpeterson** [pretzelhands/gatsby-starter-semantic-ui#1]
Hi there,

I'm using semantic-ui-react in a Gatsby app and was looking into ways to theme it... so naturally I stumbled upon this project 🙂

I'm running into an issue where (I think) the LESS is failing... I have zero experience with LESS, so I'm not exactly sure where to go with the error message.

I started a new Gatsby app using your starter, and get the following when running `gatsby develop`. My `package.json` exactly matches the one in this repo.

```shell
~/apps/test-apps/semantic-ui
❯ gatsby develop
Something is already running at port 8000
Would you like to run the app at another port instead? [Y/n]
success open and validate gatsby-config — 0.014 s
success load plugins — 0.138 s
success onPreInit — 0.129 s
success delete html and css files from previous builds — 0.009 s
success initialize cache — 0.017 s
success copy gatsby files — 0.374 s
success onPreBootstrap — 0.004 s
success source and transform nodes — 0.015 s
success building schema — 0.417 s
success createPages — 0.001 s
success createPagesStatefully — 0.025 s
success onPreExtractQueries — 0.000 s
success update schema — 0.062 s
success extract queries from components — 0.064 s
success run graphql queries — 0.037 s — 6/6 170.73 queries/second
success write out page data — 0.005 s
success write out redirect data — 0.003 s
success onPostBootstrap — 0.004 s

info bootstrap finished - 12.565 s

 ERROR  Failed to compile with 1 errors                          9:22:26 AM

 error  in ./node_modules/semantic-ui-less/semantic.less

Module build failed (from ./node_modules/less-loader/dist/cjs.js):



@theme: @@element;
      ^
Recursive variable definition for @placeholder
      in /Users/josh6643/apps/test-apps/semantic-ui/node_modules/semantic-ui-less/theme.less (line 9, column 8)

 @ ./node_modules/semantic-ui-less/semantic.less 2:14-172 21:1-42:3 22:19-177
 @ ./src/components/layout.js
 @ ./src/pages/404.js
 @ ./.cache/sync-requires.js
 @ ./.cache/app.js
 @ multi ./node_modules/react-hot-loader/patch.js (webpack)-hot-middleware/client.js?path=http://localhost:8002/__webpack_hmr&reload=true&overlay=false ./.cache/app

✖ ｢wdm｣:
ERROR in ./node_modules/semantic-ui-less/semantic.less (./node_modules/css-loader??ref--12-oneOf-1-1!./node_modules/postcss-loader/lib??postcss-3!./node_modules/less-loader/dist/cjs.js??ref--12-oneOf-1-3!./node_modules/semantic-ui-less/semantic.less)
Module build failed (from ./node_modules/less-loader/dist/cjs.js):



@theme: @@element;
      ^
Recursive variable definition for @placeholder
      in /Users/josh6643/apps/test-apps/semantic-ui/node_modules/semantic-ui-less/theme.less (line 9, column 8)
 @ ./node_modules/semantic-ui-less/semantic.less 2:14-172 21:1-42:3 22:19-177
 @ ./src/components/layout.js
 @ ./src/pages/404.js
 @ ./.cache/sync-requires.js
 @ ./.cache/app.js
 @ multi ./node_modules/react-hot-loader/patch.js (webpack)-hot-middleware/client.js?path=http://localhost:8002/__webpack_hmr&reload=true&overlay=false ./.cache/app
ℹ ｢wdm｣: Failed to compile.
```

Any ideas? Thanks in advance!

**Comment by jpeterson** [comment]
I think my issue was due to some discrepancies between versions of various dependencies (i.e. semantic-ui-less theme files changed)... all good after manually copying theme less files out of node_modules and into my app.

**Comment by pretzelhands** [comment]
Hey folks!

I updated the dependencies and adjusted the config of the default theme provided with the starter. Everything should be working again fine now. I presume there were some incompatible changes between Semantic UI versions.

I hope this resolves any issues that were had by either of you!

**Comment by james-millner** [comment]
I'm still getting this issue when building, however, I'm on an older version of semantic-ui-less: 2.2.14

**Comment by james-millner** [comment]
Is there supposed to be two @ symbols when looking at theme.less? 

`/*******************************
        Import Directives
*******************************/

/*------------------
       Theme
-------------------*/

@theme: @@element;`

**Comment by james-millner** [comment]
Hi Again, 

After fully removing semantic-ui-less from my package.json file, building and then packaging. Following I reinsert it the problem magically disappears!

**Comment by james-millner** [comment]
[INFO] Running 'webpack.js ' in /home/jamesmi/{OMITTED}

[INFO] Hash: 08d2bf5da5d1e8408cbc
[INFO] Version: webpack 2.7.0
[INFO] Time: 29435ms
[INFO]                              Asset       Size  Chunks                    Chunk Names
[INFO]     bundle.08d2bf5da5d1e8408cbc.js    7.72 MB       0  [emitted]  [big]  app
[INFO] bundle.08d2bf5da5d1e8408cbc.js.map    7.63 MB       0  [emitted]         app
[INFO]                         index.html  785 bytes          [emitted]         
[INFO] [./node_modules/node-libs-browser/node_modules/process/browser.js] ./~/node-libs-browser/~/process/browser.js 5.42 kB {0} [built]
[INFO] [./node_modules/react-dom/index.js] ./~/react-dom/index.js 59 bytes {0} [built]
[INFO] [./node_modules/react-hot-loader/index.js] ./~/react-hot-loader/index.js 40 bytes {0} [built]
[INFO] [./node_modules/react-hot-loader/lib/index.js] ./~/react-hot-loader/lib/index.js 209 bytes {0} [built]
[INFO] [./node_modules/react-hot-loader/lib/patch.js] ./~/react-hot-loader/lib/patch.js 209 bytes {0} [built]
[INFO] [./node_modules/react-hot-loader/patch.js] ./~/react-hot-loader/patch.js 40 bytes {0} [built]
[INFO] [./node_modules/react-toastify/lib/index.js] ./~/react-toastify/lib/index.js 628 bytes {0} [built]
[INFO] [./node_modules/react-vis/dist/style.css] ./~/react-vis/dist/style.css 859 bytes {0} [built]
[INFO] [./node_modules/react/react.js] ./~/react/react.js 56 bytes {0} [built]
[INFO] [./node_modules/semantic-ui-less/semantic.less] ./~/semantic-ui-less/semantic.less 963 bytes {0} [built] [failed] [1 error]
[INFO] [./src/main/js/app/containers/App.js] ./src/main/js/app/containers/App.js 3.33 kB {0} [built]
[INFO] [./src/main/js/app/containers/LoggedInApp.js] ./src/main/js/app/containers/LoggedInApp.js 8.06 kB {0} [built]
[INFO]    [0] multi react-hot-loader/patch ./src/main/js/app 40 bytes {0} [built]
[INFO] [./src/main/js/app/index.css] ./src/main/js/app/index.css 935 bytes {0} [built]
[INFO] [./src/main/js/app/index.js] ./src/main/js/app/index.js 900 bytes {0} [built]
[INFO]     + 1955 hidden modules
[INFO] 
[INFO] ERROR in ./~/semantic-ui-less/semantic.less
[INFO] Module build failed: 
[INFO] 
[INFO] 
[INFO] @theme: @@element;
[INFO]       ^
[INFO] Recursive variable definition for @placeholder

**Comment by danatemple** [comment]
@pretzelhands I am also running into this. Copying theme files from node_modules has so far not helped.

Can you elaborate on "I updated the dependencies and adjusted the config of the default theme provided with the starter. " ?

Much appreciated.

**Comment by JordanHansen** [comment]
@danatemple Not sure if you are still running into the issue or if you've made it past it, but I ran into that same error, and adding @placeholder: 'default'; to my theme.config fixed.
